<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Manual invoices (Sprint 9 — billing UX).
 *
 * Until now every invoice was generated automatically by the billing hook as sessions
 * became billable, and every line item was hard-tied to a session_id. This adds a second,
 * user-driven class of invoice:
 *
 *   - invoices.kind  : 'AUTO'   = generated by Invoicing::onSessionBillable (unchanged path)
 *                      'MANUAL' = created by an operator (itemized bill OR advance payment)
 *
 *   - invoice_line_items.session_id / student_id become nullable so an itemized manual line
 *     ("Registration fee") need not point at a concrete session/student. Advance-payment
 *     lines still carry their source session_id.
 *
 *   - The one-invoice-per-payer-per-month unique index is narrowed to AUTO only; an operator
 *     may raise any number of manual bills for the same payer/period without colliding with
 *     the automatic monthly invoice.
 *
 *   - app.public_invoice_by_token() switches its students join to a LEFT join so a manual
 *     line with a null student_id is still returned on the public page.
 *
 *   - Seeds the new invoice.create capability and grants it to ACADEMY_OWNER (idempotent, so
 *     it lands on existing databases without re-running the demo seeder).
 */
return new class extends Migration
{
    public function up(): void
    {
        // ------------------------------------------------------------------
        // 1 — kind discriminator + nullable line-item links
        // ------------------------------------------------------------------
        DB::unprepared(<<<'SQL'
            alter table invoices
                add column if not exists kind text not null default 'AUTO';

            alter table invoices
                drop constraint if exists invoices_kind_chk;
            alter table invoices
                add constraint invoices_kind_chk check (kind in ('AUTO', 'MANUAL'));

            alter table invoice_line_items
                alter column session_id drop not null,
                alter column student_id drop not null;
        SQL);

        // ------------------------------------------------------------------
        // 2 — narrow the per-payer-per-month uniqueness to automatic invoices
        // ------------------------------------------------------------------
        DB::unprepared(<<<'SQL'
            drop index if exists invoices_payer_period_uidx;
            create unique index invoices_payer_period_uidx
              on invoices (academy_id, coalesce(guardian_id, student_id), period_year, period_month)
              where kind = 'AUTO';
        SQL);

        // ------------------------------------------------------------------
        // 3 — public invoice function: LEFT join students (null-safe line items)
        // ------------------------------------------------------------------
        DB::unprepared(<<<'SQL'
            create or replace function app.public_invoice_by_token(token text)
            returns json
            language plpgsql
            security definer
            set search_path = public, pg_catalog
            as $$
            declare
                v_invoice   record;
                v_result    json;
            begin
                select
                    i.id,
                    i.status,
                    i.period_year,
                    i.period_month,
                    i.currency,
                    i.subtotal_minor,
                    i.total_minor,
                    i.amount_paid_minor,
                    i.sent_at,
                    i.sent_channel,
                    i.closed_at,
                    i.paid_at,
                    i.payment_method,
                    i.payment_reason,
                    a.name                                                         as academy_name,
                    coalesce(g.full_name,  s_payer.full_name)                      as payer_name,
                    coalesce(g.whatsapp_phone, s_payer.whatsapp_phone)             as payer_whatsapp
                into v_invoice
                from invoices         i
                join academies        a       on a.id = i.academy_id
                left join guardians   g       on g.id = i.guardian_id
                left join students    s_payer on s_payer.id = i.student_id
                where i.public_token = token
                limit 1;

                if not found then
                    return null;
                end if;

                select json_build_object(
                    'id',                v_invoice.id,
                    'status',            v_invoice.status,
                    'period_year',       v_invoice.period_year,
                    'period_month',      v_invoice.period_month,
                    'currency',          v_invoice.currency,
                    'subtotal_minor',    v_invoice.subtotal_minor,
                    'total_minor',       v_invoice.total_minor,
                    'amount_paid_minor', v_invoice.amount_paid_minor,
                    'sent_at',           v_invoice.sent_at,
                    'sent_channel',      v_invoice.sent_channel,
                    'closed_at',         v_invoice.closed_at,
                    'paid_at',           v_invoice.paid_at,
                    'payment_method',    v_invoice.payment_method,
                    'payment_reason',    v_invoice.payment_reason,
                    'academy_name',      v_invoice.academy_name,
                    'payer_name',        v_invoice.payer_name,
                    'payer_whatsapp',    v_invoice.payer_whatsapp,
                    'line_items',        coalesce(
                        (
                            select json_agg(
                                json_build_object(
                                    'id',           li.id,
                                    'session_id',   li.session_id,
                                    'student_id',   li.student_id,
                                    'student_name', s.full_name,
                                    'description',  li.description,
                                    'amount_minor', li.amount_minor,
                                    'currency',     li.currency,
                                    'session_date', li.session_date
                                )
                                order by li.session_date asc nulls last,
                                         li.created_at   asc
                            )
                            from invoice_line_items li
                            left join students      s  on s.id = li.student_id
                            where li.invoice_id = v_invoice.id
                        ),
                        '[]'::json
                    )
                )
                into v_result;

                return v_result;
            end;
            $$;
        SQL);

        $bypass = (string) config('database.rls.bypass_role', '');
        if ($bypass !== '' && preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $bypass)) {
            DB::unprepared("alter function app.public_invoice_by_token(text) owner to {$bypass};");
        }

        // The new invoice.create capability is seeded through PermissionCatalog (the catalog
        // tables are RLS-protected and only writable via the Super-Admin seeder path), so there
        // is intentionally no permissions DML here.
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
            drop index if exists invoices_payer_period_uidx;
            create unique index invoices_payer_period_uidx
              on invoices (academy_id, coalesce(guardian_id, student_id), period_year, period_month);

            alter table invoices drop constraint if exists invoices_kind_chk;
            alter table invoices drop column if exists kind;
        SQL);
    }
};
