export interface Country {
  code: string;     // ISO-3166-1 alpha-2
  name: string;
  dialCode: string; // E.164 prefix, e.g. "+966"
  flag: string;     // Unicode flag emoji
  currency: string; // ISO-4217, e.g. "SAR"
}

export const COUNTRIES: readonly Country[] = [
  // ── Middle East ──────────────────────────────────────────────────────────────
  { code: "SA", name: "Saudi Arabia",           dialCode: "+966", flag: "🇸🇦", currency: "SAR" },
  { code: "AE", name: "United Arab Emirates",   dialCode: "+971", flag: "🇦🇪", currency: "AED" },
  { code: "KW", name: "Kuwait",                 dialCode: "+965", flag: "🇰🇼", currency: "KWD" },
  { code: "QA", name: "Qatar",                  dialCode: "+974", flag: "🇶🇦", currency: "QAR" },
  { code: "BH", name: "Bahrain",                dialCode: "+973", flag: "🇧🇭", currency: "BHD" },
  { code: "OM", name: "Oman",                   dialCode: "+968", flag: "🇴🇲", currency: "OMR" },
  { code: "JO", name: "Jordan",                 dialCode: "+962", flag: "🇯🇴", currency: "JOD" },
  { code: "IQ", name: "Iraq",                   dialCode: "+964", flag: "🇮🇶", currency: "IQD" },
  { code: "LB", name: "Lebanon",                dialCode: "+961", flag: "🇱🇧", currency: "LBP" },
  { code: "SY", name: "Syria",                  dialCode: "+963", flag: "🇸🇾", currency: "SYP" },
  { code: "YE", name: "Yemen",                  dialCode: "+967", flag: "🇾🇪", currency: "YER" },
  { code: "PS", name: "Palestine",              dialCode: "+970", flag: "🇵🇸", currency: "ILS" },
  // ── North Africa ─────────────────────────────────────────────────────────────
  { code: "EG", name: "Egypt",                  dialCode: "+20",  flag: "🇪🇬", currency: "EGP" },
  { code: "MA", name: "Morocco",                dialCode: "+212", flag: "🇲🇦", currency: "MAD" },
  { code: "TN", name: "Tunisia",                dialCode: "+216", flag: "🇹🇳", currency: "TND" },
  { code: "DZ", name: "Algeria",                dialCode: "+213", flag: "🇩🇿", currency: "DZD" },
  { code: "LY", name: "Libya",                  dialCode: "+218", flag: "🇱🇾", currency: "LYD" },
  { code: "SD", name: "Sudan",                  dialCode: "+249", flag: "🇸🇩", currency: "SDG" },
  // ── South Asia ───────────────────────────────────────────────────────────────
  { code: "IN", name: "India",                  dialCode: "+91",  flag: "🇮🇳", currency: "INR" },
  { code: "PK", name: "Pakistan",               dialCode: "+92",  flag: "🇵🇰", currency: "PKR" },
  { code: "BD", name: "Bangladesh",             dialCode: "+880", flag: "🇧🇩", currency: "BDT" },
  { code: "LK", name: "Sri Lanka",              dialCode: "+94",  flag: "🇱🇰", currency: "LKR" },
  { code: "NP", name: "Nepal",                  dialCode: "+977", flag: "🇳🇵", currency: "NPR" },
  // ── East / South-East Asia ───────────────────────────────────────────────────
  { code: "CN", name: "China",                  dialCode: "+86",  flag: "🇨🇳", currency: "CNY" },
  { code: "JP", name: "Japan",                  dialCode: "+81",  flag: "🇯🇵", currency: "JPY" },
  { code: "KR", name: "South Korea",            dialCode: "+82",  flag: "🇰🇷", currency: "KRW" },
  { code: "MY", name: "Malaysia",               dialCode: "+60",  flag: "🇲🇾", currency: "MYR" },
  { code: "SG", name: "Singapore",              dialCode: "+65",  flag: "🇸🇬", currency: "SGD" },
  { code: "ID", name: "Indonesia",              dialCode: "+62",  flag: "🇮🇩", currency: "IDR" },
  { code: "PH", name: "Philippines",            dialCode: "+63",  flag: "🇵🇭", currency: "PHP" },
  { code: "TH", name: "Thailand",               dialCode: "+66",  flag: "🇹🇭", currency: "THB" },
  { code: "VN", name: "Vietnam",                dialCode: "+84",  flag: "🇻🇳", currency: "VND" },
  // ── Europe ───────────────────────────────────────────────────────────────────
  { code: "GB", name: "United Kingdom",         dialCode: "+44",  flag: "🇬🇧", currency: "GBP" },
  { code: "FR", name: "France",                 dialCode: "+33",  flag: "🇫🇷", currency: "EUR" },
  { code: "DE", name: "Germany",                dialCode: "+49",  flag: "🇩🇪", currency: "EUR" },
  { code: "IT", name: "Italy",                  dialCode: "+39",  flag: "🇮🇹", currency: "EUR" },
  { code: "ES", name: "Spain",                  dialCode: "+34",  flag: "🇪🇸", currency: "EUR" },
  { code: "NL", name: "Netherlands",            dialCode: "+31",  flag: "🇳🇱", currency: "EUR" },
  { code: "BE", name: "Belgium",                dialCode: "+32",  flag: "🇧🇪", currency: "EUR" },
  { code: "CH", name: "Switzerland",            dialCode: "+41",  flag: "🇨🇭", currency: "CHF" },
  { code: "SE", name: "Sweden",                 dialCode: "+46",  flag: "🇸🇪", currency: "SEK" },
  { code: "NO", name: "Norway",                 dialCode: "+47",  flag: "🇳🇴", currency: "NOK" },
  { code: "DK", name: "Denmark",                dialCode: "+45",  flag: "🇩🇰", currency: "DKK" },
  { code: "FI", name: "Finland",                dialCode: "+358", flag: "🇫🇮", currency: "EUR" },
  { code: "PL", name: "Poland",                 dialCode: "+48",  flag: "🇵🇱", currency: "PLN" },
  { code: "PT", name: "Portugal",               dialCode: "+351", flag: "🇵🇹", currency: "EUR" },
  { code: "TR", name: "Turkey",                 dialCode: "+90",  flag: "🇹🇷", currency: "TRY" },
  { code: "RU", name: "Russia",                 dialCode: "+7",   flag: "🇷🇺", currency: "RUB" },
  { code: "UA", name: "Ukraine",                dialCode: "+380", flag: "🇺🇦", currency: "UAH" },
  { code: "GR", name: "Greece",                 dialCode: "+30",  flag: "🇬🇷", currency: "EUR" },
  // ── Americas ──────────────────────────────────────────────────────────────────
  { code: "US", name: "United States",          dialCode: "+1",   flag: "🇺🇸", currency: "USD" },
  { code: "CA", name: "Canada",                 dialCode: "+1",   flag: "🇨🇦", currency: "CAD" },
  { code: "BR", name: "Brazil",                 dialCode: "+55",  flag: "🇧🇷", currency: "BRL" },
  { code: "MX", name: "Mexico",                 dialCode: "+52",  flag: "🇲🇽", currency: "MXN" },
  { code: "AR", name: "Argentina",              dialCode: "+54",  flag: "🇦🇷", currency: "ARS" },
  { code: "CO", name: "Colombia",               dialCode: "+57",  flag: "🇨🇴", currency: "COP" },
  { code: "CL", name: "Chile",                  dialCode: "+56",  flag: "🇨🇱", currency: "CLP" },
  // ── Africa ───────────────────────────────────────────────────────────────────
  { code: "ZA", name: "South Africa",           dialCode: "+27",  flag: "🇿🇦", currency: "ZAR" },
  { code: "NG", name: "Nigeria",                dialCode: "+234", flag: "🇳🇬", currency: "NGN" },
  { code: "KE", name: "Kenya",                  dialCode: "+254", flag: "🇰🇪", currency: "KES" },
  { code: "GH", name: "Ghana",                  dialCode: "+233", flag: "🇬🇭", currency: "GHS" },
  { code: "ET", name: "Ethiopia",               dialCode: "+251", flag: "🇪🇹", currency: "ETB" },
  // ── Oceania ───────────────────────────────────────────────────────────────────
  { code: "AU", name: "Australia",              dialCode: "+61",  flag: "🇦🇺", currency: "AUD" },
  { code: "NZ", name: "New Zealand",            dialCode: "+64",  flag: "🇳🇿", currency: "NZD" },
] as const;

export interface Currency {
  code: string;
  name: string;
}

export const CURRENCIES: readonly Currency[] = [
  { code: "SAR", name: "Saudi Riyal" },
  { code: "AED", name: "UAE Dirham" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "ILS", name: "Israeli Shekel" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "SDG", name: "Sudanese Pound" },
  { code: "INR", name: "Indian Rupee" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "KRW", name: "South Korean Won" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "THB", name: "Thai Baht" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "DKK", name: "Danish Krone" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "COP", name: "Colombian Peso" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "ZAR", name: "South African Rand" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "ETB", name: "Ethiopian Birr" },
] as const;
